### ISSUE TITLE
Binary action search

### ISSUE THREAD

**Issue by liquidnode** [vub-ai-lab/bdpi#1]
It would be nice if the code for the inverted pendulum experiment (or continuous actions in general) mentioned in the paper is added. The exact way of the Binary Action Search implementation would be interesting, especially in the Q-learning part of the BDPI algorithm, since I'm not sure if the Q-function needs the current depth of the binary search as an additional input to properly work or if different Q-functions for different depths are used.

**Comment by steckdenis** [comment]
Good remark! I was so busy writing the camera-ready version of the paper that I forgot to push the very latest version of the algorithm to this repository (binary action search included). I will do that on Monday, when I will have access to my lab's private Git repo.

To already answer your question, the agent does not need to know the current depth of the search, but it has to observe the current candidate action. For instance, if the optimal action in a particular state s is "0.778", then, the Q-Value of "increase" will be higher than "decrease" for any (s, x) extended-state tuple with x < 0.778. The order of the Q-Values is reversed when x > 0.778. So, basically, the agent learns which continuous actions are too high or too low, triggers the discrete action that increases or decreases it, and does not need to know by how much the continuous action is increased or decreased.

**Comment by liquidnode** [comment]
It makes sense that the Q-Value must be higher or lower based on x and the optimal action. But let's say for example that the optimal action of 0.778 has a reward of 1 and this is the last step of the episode. We also set gamma=0.9. This means at the end of the search the best Q-Value must be 1. The step before that it must be 0.9*1. So depending on the search depth different highest Q-Values must exist. And without this knowlege the Q-function can only guess in which search step it is, so it learns a kinda stochastic policy and Q-Value, which could (?) degrade its performance.

Likely its not that big of a problem, because as you said the Q-function has to only get the direction right. I will still experiment a bit with including depth information, maybe it will increase the performance of the algorithm.

Anyway thanks already for pushing the Binary action search code. Can't wait to look into it 👍

**Comment by steckdenis** [comment]
Humm, that remark about the discount factor is super interesting. I have uploaded the binary action search code (gym_envs/contwrapper.py). It is automatically used by BDPI when the Gym environment reports continuous actions. Beware that the code is likely buggy or incomplete. I've spent maybe 30 minutes trying to apply BDPI to continuous actions.
